// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Pipelines
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PipelinesGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The pipeline creation time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>The ID of the pipeline</summary>
        public int? Id { get; set; }
        /// <summary>Whether deal probability is disabled or enabled for this pipeline</summary>
        public bool? IsDealProbabilityEnabled { get; set; }
        /// <summary>Whether this pipeline is marked as deleted or not</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>The name of the pipeline</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Defines the order of pipelines. The pipeline with the lowest `order_nr` is considered the default.</summary>
        public int? OrderNr { get; set; }
        /// <summary>The pipeline update time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Pipelines.PipelinesGetResponse_data"/> and sets the default values.
        /// </summary>
        public PipelinesGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Pipelines.PipelinesGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Pipelines.PipelinesGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Pipelines.PipelinesGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_deal_probability_enabled", n => { IsDealProbabilityEnabled = n.GetBoolValue(); } },
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "order_nr", n => { OrderNr = n.GetIntValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_deal_probability_enabled", IsDealProbabilityEnabled);
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("order_nr", OrderNr);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
