// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item
{
    /// <summary>
    /// UI visibility settings (only included when requested via include_fields parameter)
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithField_codePatchResponse_data_ui_visibility : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the field is shown in the add modal</summary>
        public bool? AddVisibleFlag { get; set; }
        /// <summary>Whether the field is shown in the deal details view</summary>
        public bool? DealDetailVisibleFlag { get; set; }
        /// <summary>Whether the field is shown in the details view</summary>
        public bool? DetailsVisibleFlag { get; set; }
        /// <summary>Whether the field is shown in the organization details view</summary>
        public bool? OrgDetailVisibleFlag { get; set; }
        /// <summary>Whether the field is shown in the person details view</summary>
        public bool? PersonDetailVisibleFlag { get; set; }
        /// <summary>Configuration for showing the field in the add deal dialog</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_deal_dialog? ShowInAddDealDialog { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_deal_dialog ShowInAddDealDialog { get; set; }
#endif
        /// <summary>Configuration for showing the field in the add person dialog</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_person_dialog? ShowInAddPersonDialog { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_person_dialog ShowInAddPersonDialog { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility"/> and sets the default values.
        /// </summary>
        public WithField_codePatchResponse_data_ui_visibility()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_visible_flag", n => { AddVisibleFlag = n.GetBoolValue(); } },
                { "deal_detail_visible_flag", n => { DealDetailVisibleFlag = n.GetBoolValue(); } },
                { "details_visible_flag", n => { DetailsVisibleFlag = n.GetBoolValue(); } },
                { "org_detail_visible_flag", n => { OrgDetailVisibleFlag = n.GetBoolValue(); } },
                { "person_detail_visible_flag", n => { PersonDetailVisibleFlag = n.GetBoolValue(); } },
                { "show_in_add_deal_dialog", n => { ShowInAddDealDialog = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_deal_dialog>(global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_deal_dialog.CreateFromDiscriminatorValue); } },
                { "show_in_add_person_dialog", n => { ShowInAddPersonDialog = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_person_dialog>(global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_person_dialog.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("add_visible_flag", AddVisibleFlag);
            writer.WriteBoolValue("deal_detail_visible_flag", DealDetailVisibleFlag);
            writer.WriteBoolValue("details_visible_flag", DetailsVisibleFlag);
            writer.WriteBoolValue("org_detail_visible_flag", OrgDetailVisibleFlag);
            writer.WriteBoolValue("person_detail_visible_flag", PersonDetailVisibleFlag);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_deal_dialog>("show_in_add_deal_dialog", ShowInAddDealDialog);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.OrganizationFields.Item.WithField_codePatchResponse_data_ui_visibility_show_in_add_person_dialog>("show_in_add_person_dialog", ShowInAddPersonDialog);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
