// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.DealFields.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WithField_codePatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Field description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Field name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldName { get; set; }
#nullable restore
#else
        public string FieldName { get; set; }
#endif
        /// <summary>Configuration for highlighting the field at specific stages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_important_fields? ImportantFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_important_fields ImportantFields { get; set; }
#endif
        /// <summary>Required fields configuration for marking the field as mandatory when interacted with in the Pipedrive web UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_required_fields? RequiredFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_required_fields RequiredFields { get; set; }
#endif
        /// <summary>UI visibility settings for the field. Controls where the field appears in the Pipedrive web UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_ui_visibility? UiVisibility { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_ui_visibility UiVisibility { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody"/> and sets the default values.
        /// </summary>
        public WithField_codePatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "description", n => { Description = n.GetStringValue(); } },
                { "field_name", n => { FieldName = n.GetStringValue(); } },
                { "important_fields", n => { ImportantFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_important_fields>(global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_important_fields.CreateFromDiscriminatorValue); } },
                { "required_fields", n => { RequiredFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_required_fields>(global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_required_fields.CreateFromDiscriminatorValue); } },
                { "ui_visibility", n => { UiVisibility = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_ui_visibility>(global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_ui_visibility.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("field_name", FieldName);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_important_fields>("important_fields", ImportantFields);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_required_fields>("required_fields", RequiredFields);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.DealFields.Item.WithField_codePatchRequestBody_ui_visibility>("ui_visibility", UiVisibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
