// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Deals
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DealsPostResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Only available in Growth and above plansThe Annual Contract Value of the dealNull if there are no products attached to the deal</summary>
        public double? Acv { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation date and time of the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>Only available in Growth and above plansThe Annual Recurring Revenue of the dealNull if there are no products attached to the deal</summary>
        public double? Arr { get; set; }
        /// <summary>The ID of your Marketing channel this Deal was created from. Recognized Marketing channels can be configured in your &lt;a href=&quot;https://app.pipedrive.com/settings/fields&quot; target=&quot;_blank&quot; rel=&quot;noopener noreferrer&quot;&gt;Company settings&lt;/a&gt;.</summary>
        public int? Channel { get; set; }
        /// <summary>The optional ID to further distinguish the Marketing channel.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ChannelId { get; set; }
#nullable restore
#else
        public string ChannelId { get; set; }
#endif
        /// <summary>The date and time of closing the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CloseTime { get; set; }
#nullable restore
#else
        public string CloseTime { get; set; }
#endif
        /// <summary>The currency associated with the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>An object where each key represents a custom field. All custom fields are referenced as randomly generated 40-character hashes. To clear a custom field value, set it to `null`. For multi-option fields (field type `set`), use `null` to clear the selection — sending an empty array `[]` is not supported and will result in a validation error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data_custom_fields CustomFields { get; set; }
#endif
        /// <summary>The expected close date of the deal</summary>
        public Date? ExpectedCloseDate { get; set; }
        /// <summary>The ID of the deal</summary>
        public int? Id { get; set; }
        /// <summary>Whether the deal is archived or not</summary>
        public bool? IsArchived { get; set; }
        /// <summary>Whether the deal is deleted or not</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>The IDs of labels assigned to the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? LabelIds { get; set; }
#nullable restore
#else
        public List<int?> LabelIds { get; set; }
#endif
        /// <summary>The reason for losing the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LostReason { get; set; }
#nullable restore
#else
        public string LostReason { get; set; }
#endif
        /// <summary>The date and time of changing the deal status as lost</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LostTime { get; set; }
#nullable restore
#else
        public string LostTime { get; set; }
#endif
        /// <summary>Only available in Growth and above plansThe Monthly Recurring Revenue of the dealNull if there are no products attached to the deal</summary>
        public double? Mrr { get; set; }
        /// <summary>The ID of the organization linked to the deal</summary>
        public int? OrgId { get; set; }
        /// <summary>The way this Deal was created. `origin` field is set by Pipedrive when Deal is created and cannot be changed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Origin { get; set; }
#nullable restore
#else
        public string Origin { get; set; }
#endif
        /// <summary>The optional ID to further distinguish the origin of the deal - e.g. Which API integration created this Deal.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OriginId { get; set; }
#nullable restore
#else
        public string OriginId { get; set; }
#endif
        /// <summary>The ID of the user who owns the deal</summary>
        public int? OwnerId { get; set; }
        /// <summary>The ID of the person linked to the deal</summary>
        public int? PersonId { get; set; }
        /// <summary>The ID of the pipeline associated with the deal</summary>
        public int? PipelineId { get; set; }
        /// <summary>The success probability percentage of the deal</summary>
        public double? Probability { get; set; }
        /// <summary>The ID of the lead if the deal was converted from a lead. Only included when requested via include_fields parameter.</summary>
        public Guid? SourceLeadId { get; set; }
        /// <summary>The last updated date and time of the deal stage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StageChangeTime { get; set; }
#nullable restore
#else
        public string StageChangeTime { get; set; }
#endif
        /// <summary>The ID of the deal stage</summary>
        public int? StageId { get; set; }
        /// <summary>The status of the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The title of the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The last updated date and time of the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>The value of the deal</summary>
        public double? Value { get; set; }
        /// <summary>The visibility of the deal</summary>
        public int? VisibleTo { get; set; }
        /// <summary>The date and time of changing the deal status as won</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WonTime { get; set; }
#nullable restore
#else
        public string WonTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data"/> and sets the default values.
        /// </summary>
        public DealsPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "acv", n => { Acv = n.GetDoubleValue(); } },
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "arr", n => { Arr = n.GetDoubleValue(); } },
                { "channel", n => { Channel = n.GetIntValue(); } },
                { "channel_id", n => { ChannelId = n.GetStringValue(); } },
                { "close_time", n => { CloseTime = n.GetStringValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data_custom_fields>(global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data_custom_fields.CreateFromDiscriminatorValue); } },
                { "expected_close_date", n => { ExpectedCloseDate = n.GetDateValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_archived", n => { IsArchived = n.GetBoolValue(); } },
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "label_ids", n => { LabelIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "lost_reason", n => { LostReason = n.GetStringValue(); } },
                { "lost_time", n => { LostTime = n.GetStringValue(); } },
                { "mrr", n => { Mrr = n.GetDoubleValue(); } },
                { "org_id", n => { OrgId = n.GetIntValue(); } },
                { "origin", n => { Origin = n.GetStringValue(); } },
                { "origin_id", n => { OriginId = n.GetStringValue(); } },
                { "owner_id", n => { OwnerId = n.GetIntValue(); } },
                { "person_id", n => { PersonId = n.GetIntValue(); } },
                { "pipeline_id", n => { PipelineId = n.GetIntValue(); } },
                { "probability", n => { Probability = n.GetDoubleValue(); } },
                { "source_lead_id", n => { SourceLeadId = n.GetGuidValue(); } },
                { "stage_change_time", n => { StageChangeTime = n.GetStringValue(); } },
                { "stage_id", n => { StageId = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
                { "value", n => { Value = n.GetDoubleValue(); } },
                { "visible_to", n => { VisibleTo = n.GetIntValue(); } },
                { "won_time", n => { WonTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("acv", Acv);
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteDoubleValue("arr", Arr);
            writer.WriteIntValue("channel", Channel);
            writer.WriteStringValue("channel_id", ChannelId);
            writer.WriteStringValue("close_time", CloseTime);
            writer.WriteStringValue("currency", Currency);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.DealsPostResponse_data_custom_fields>("custom_fields", CustomFields);
            writer.WriteDateValue("expected_close_date", ExpectedCloseDate);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_archived", IsArchived);
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteCollectionOfPrimitiveValues<int?>("label_ids", LabelIds);
            writer.WriteStringValue("lost_reason", LostReason);
            writer.WriteStringValue("lost_time", LostTime);
            writer.WriteDoubleValue("mrr", Mrr);
            writer.WriteIntValue("org_id", OrgId);
            writer.WriteStringValue("origin", Origin);
            writer.WriteStringValue("origin_id", OriginId);
            writer.WriteIntValue("owner_id", OwnerId);
            writer.WriteIntValue("person_id", PersonId);
            writer.WriteIntValue("pipeline_id", PipelineId);
            writer.WriteDoubleValue("probability", Probability);
            writer.WriteGuidValue("source_lead_id", SourceLeadId);
            writer.WriteStringValue("stage_change_time", StageChangeTime);
            writer.WriteIntValue("stage_id", StageId);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteDoubleValue("value", Value);
            writer.WriteIntValue("visible_to", VisibleTo);
            writer.WriteStringValue("won_time", WonTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
