// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pipedrive.OpenApiClient.Leads.Item.ConvertNamespace;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Leads.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \leads\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LeadsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The convert property</summary>
        public global::Soenneker.Pipedrive.OpenApiClient.Leads.Item.ConvertNamespace.ConvertRequestBuilder Convert
        {
            get => new global::Soenneker.Pipedrive.OpenApiClient.Leads.Item.ConvertNamespace.ConvertRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Leads.Item.LeadsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/leads/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Leads.Item.LeadsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LeadsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/leads/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
