// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Projects
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectsPostResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation date and time of the project in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>The date and time the project was archived in ISO 8601 format. If not archived, this field is null.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArchiveTime { get; set; }
#nullable restore
#else
        public string ArchiveTime { get; set; }
#endif
        /// <summary>The ID of the board this project is associated with</summary>
        public int? BoardId { get; set; }
        /// <summary>An object where each key represents a custom field. All custom fields are referenced as randomly generated 40-character hashes. To clear a custom field value, set it to `null`. For multi-option fields (field type `set`), use `null` to clear the selection — sending an empty array `[]` is not supported and will result in a validation error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data_custom_fields CustomFields { get; set; }
#endif
        /// <summary>An array of IDs of the deals this project is associated with</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? DealIds { get; set; }
#nullable restore
#else
        public List<int?> DealIds { get; set; }
#endif
        /// <summary>The description of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The end date of the project. Format: YYYY-MM-DD</summary>
        public Date? EndDate { get; set; }
        /// <summary>The health status of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HealthStatus { get; set; }
#nullable restore
#else
        public string HealthStatus { get; set; }
#endif
        /// <summary>The ID of the project</summary>
        public int? Id { get; set; }
        /// <summary>An array of IDs of the labels this project has</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? LabelIds { get; set; }
#nullable restore
#else
        public List<int?> LabelIds { get; set; }
#endif
        /// <summary>An array of IDs of the organizations this project is associated with</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? OrgIds { get; set; }
#nullable restore
#else
        public List<int?> OrgIds { get; set; }
#endif
        /// <summary>The ID of the user who owns the project</summary>
        public int? OwnerId { get; set; }
        /// <summary>An array of IDs of the persons this project is associated with</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? PersonIds { get; set; }
#nullable restore
#else
        public List<int?> PersonIds { get; set; }
#endif
        /// <summary>The ID of the phase this project is associated with</summary>
        public int? PhaseId { get; set; }
        /// <summary>The start date of the project. Format: YYYY-MM-DD</summary>
        public Date? StartDate { get; set; }
        /// <summary>The status of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The date and time of the last status change of the project in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StatusChangeTime { get; set; }
#nullable restore
#else
        public string StatusChangeTime { get; set; }
#endif
        /// <summary>The title of the project</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The last updated date and time of the project in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data"/> and sets the default values.
        /// </summary>
        public ProjectsPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "archive_time", n => { ArchiveTime = n.GetStringValue(); } },
                { "board_id", n => { BoardId = n.GetIntValue(); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data_custom_fields>(global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data_custom_fields.CreateFromDiscriminatorValue); } },
                { "deal_ids", n => { DealIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "health_status", n => { HealthStatus = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "label_ids", n => { LabelIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "org_ids", n => { OrgIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "owner_id", n => { OwnerId = n.GetIntValue(); } },
                { "person_ids", n => { PersonIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "phase_id", n => { PhaseId = n.GetIntValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "status_change_time", n => { StatusChangeTime = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteStringValue("archive_time", ArchiveTime);
            writer.WriteIntValue("board_id", BoardId);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Projects.ProjectsPostResponse_data_custom_fields>("custom_fields", CustomFields);
            writer.WriteCollectionOfPrimitiveValues<int?>("deal_ids", DealIds);
            writer.WriteStringValue("description", Description);
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteStringValue("health_status", HealthStatus);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfPrimitiveValues<int?>("label_ids", LabelIds);
            writer.WriteCollectionOfPrimitiveValues<int?>("org_ids", OrgIds);
            writer.WriteIntValue("owner_id", OwnerId);
            writer.WriteCollectionOfPrimitiveValues<int?>("person_ids", PersonIds);
            writer.WriteIntValue("phase_id", PhaseId);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("status_change_time", StatusChangeTime);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
