// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Persons
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PersonsPostResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation date and time of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>The birthday of the person, included if contact sync is enabled for the company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Birthday { get; set; }
#nullable restore
#else
        public string Birthday { get; set; }
#endif
        /// <summary>An object where each key represents a custom field. All custom fields are referenced as randomly generated 40-character hashes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_custom_fields CustomFields { get; set; }
#endif
        /// <summary>The emails of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_emails>? Emails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_emails> Emails { get; set; }
#endif
        /// <summary>The first name of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstName { get; set; }
#nullable restore
#else
        public string FirstName { get; set; }
#endif
        /// <summary>The ID of the person</summary>
        public int? Id { get; set; }
        /// <summary>The instant messaging accounts of the person, included if contact sync is enabled for the company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_im>? Im { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_im> Im { get; set; }
#endif
        /// <summary>Whether the person is deleted or not</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>The job title of the person, included if contact sync is enabled for the company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JobTitle { get; set; }
#nullable restore
#else
        public string JobTitle { get; set; }
#endif
        /// <summary>The IDs of labels assigned to the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? LabelIds { get; set; }
#nullable restore
#else
        public List<int?> LabelIds { get; set; }
#endif
        /// <summary>The last name of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastName { get; set; }
#nullable restore
#else
        public string LastName { get; set; }
#endif
        /// <summary>The name of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Contact sync notes of the person, maximum 10 000 characters, included if contact sync is enabled for the company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Notes { get; set; }
#nullable restore
#else
        public string Notes { get; set; }
#endif
        /// <summary>The ID of the organization linked to the person</summary>
        public int? OrgId { get; set; }
        /// <summary>The ID of the user who owns the person</summary>
        public int? OwnerId { get; set; }
        /// <summary>The phones of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_phones>? Phones { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_phones> Phones { get; set; }
#endif
        /// <summary>The ID of the picture associated with the person</summary>
        public int? PictureId { get; set; }
        /// <summary>Postal address of the person, included if contact sync is enabled for the company</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_postal_address? PostalAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_postal_address PostalAddress { get; set; }
#endif
        /// <summary>The last updated date and time of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>The visibility of the person</summary>
        public int? VisibleTo { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data"/> and sets the default values.
        /// </summary>
        public PersonsPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "birthday", n => { Birthday = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_custom_fields>(global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_custom_fields.CreateFromDiscriminatorValue); } },
                { "emails", n => { Emails = n.GetCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_emails>(global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_emails.CreateFromDiscriminatorValue)?.AsList(); } },
                { "first_name", n => { FirstName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "im", n => { Im = n.GetCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_im>(global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_im.CreateFromDiscriminatorValue)?.AsList(); } },
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "job_title", n => { JobTitle = n.GetStringValue(); } },
                { "label_ids", n => { LabelIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "last_name", n => { LastName = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "notes", n => { Notes = n.GetStringValue(); } },
                { "org_id", n => { OrgId = n.GetIntValue(); } },
                { "owner_id", n => { OwnerId = n.GetIntValue(); } },
                { "phones", n => { Phones = n.GetCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_phones>(global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_phones.CreateFromDiscriminatorValue)?.AsList(); } },
                { "picture_id", n => { PictureId = n.GetIntValue(); } },
                { "postal_address", n => { PostalAddress = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_postal_address>(global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_postal_address.CreateFromDiscriminatorValue); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
                { "visible_to", n => { VisibleTo = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteStringValue("birthday", Birthday);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_custom_fields>("custom_fields", CustomFields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_emails>("emails", Emails);
            writer.WriteStringValue("first_name", FirstName);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_im>("im", Im);
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteStringValue("job_title", JobTitle);
            writer.WriteCollectionOfPrimitiveValues<int?>("label_ids", LabelIds);
            writer.WriteStringValue("last_name", LastName);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("notes", Notes);
            writer.WriteIntValue("org_id", OrgId);
            writer.WriteIntValue("owner_id", OwnerId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_phones>("phones", Phones);
            writer.WriteIntValue("picture_id", PictureId);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.PersonsPostResponse_data_postal_address>("postal_address", PostalAddress);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteIntValue("visible_to", VisibleTo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
