// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Leads.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetInclude_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "lead.was_seen")]
        #pragma warning disable CS1591
        LeadWas_seen,
        #pragma warning restore CS1591
    }
}
