// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.ActivityFields.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetInclude_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ui_visibility")]
        #pragma warning disable CS1591
        Ui_visibility,
        #pragma warning restore CS1591
    }
}
