// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Stages
{
    /// <summary>
    /// The stage object
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StagesPostResponse_data : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The stage creation time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>The number of days the deals not updated in this stage would become rotten. Applies only if the `is_deal_rot_enabled` is set.</summary>
        public int? DaysToRotten { get; set; }
        /// <summary>The success probability percentage of the deal. Used/shown when the deal weighted values are used.</summary>
        public int? DealProbability { get; set; }
        /// <summary>The ID of the stage</summary>
        public int? Id { get; set; }
        /// <summary>Whether deals in this stage can become rotten</summary>
        public bool? IsDealRotEnabled { get; set; }
        /// <summary>Whether the stage is marked as deleted or not</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>The name of the stage</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Defines the order of the stage</summary>
        public int? OrderNr { get; set; }
        /// <summary>The ID of the pipeline to add the stage to</summary>
        public int? PipelineId { get; set; }
        /// <summary>The stage update time</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Stages.StagesPostResponse_data"/> and sets the default values.
        /// </summary>
        public StagesPostResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Stages.StagesPostResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Stages.StagesPostResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Stages.StagesPostResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "days_to_rotten", n => { DaysToRotten = n.GetIntValue(); } },
                { "deal_probability", n => { DealProbability = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_deal_rot_enabled", n => { IsDealRotEnabled = n.GetBoolValue(); } },
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "order_nr", n => { OrderNr = n.GetIntValue(); } },
                { "pipeline_id", n => { PipelineId = n.GetIntValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteIntValue("days_to_rotten", DaysToRotten);
            writer.WriteIntValue("deal_probability", DealProbability);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_deal_rot_enabled", IsDealRotEnabled);
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("order_nr", OrderNr);
            writer.WriteIntValue("pipeline_id", PipelineId);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
