// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.ProjectFields
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectFieldsPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Field name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FieldName { get; set; }
#nullable restore
#else
        public string FieldName { get; set; }
#endif
        /// <summary>The type of the field&lt;table&gt;&lt;tr&gt;&lt;th&gt;Value&lt;/th&gt;&lt;th&gt;Description&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;`varchar`&lt;/td&gt;&lt;td&gt;Text (up to 255 characters)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`varchar_auto`&lt;/td&gt;&lt;td&gt;Autocomplete text (up to 255 characters)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`text`&lt;/td&gt;&lt;td&gt;Long text (up to 65k characters)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`double`&lt;/td&gt;&lt;td&gt;Numeric value&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`monetary`&lt;/td&gt;&lt;td&gt;Monetary field (has a numeric value and a currency value)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`date`&lt;/td&gt;&lt;td&gt;Date (format YYYY-MM-DD)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`set`&lt;/td&gt;&lt;td&gt;Options field with a possibility of having multiple chosen options&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`enum`&lt;/td&gt;&lt;td&gt;Options field with a single possible chosen option&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`user`&lt;/td&gt;&lt;td&gt;User field (contains a user ID of another Pipedrive user)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`org`&lt;/td&gt;&lt;td&gt;Organization field (contains an organization ID which is stored on the same account)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`people`&lt;/td&gt;&lt;td&gt;Person field (contains a person ID which is stored on the same account)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`phone`&lt;/td&gt;&lt;td&gt;Phone field (up to 255 numbers and/or characters)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`time`&lt;/td&gt;&lt;td&gt;Time field (format HH:MM:SS)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`timerange`&lt;/td&gt;&lt;td&gt;Time-range field (has a start time and end time value, both HH:MM:SS)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`daterange`&lt;/td&gt;&lt;td&gt;Date-range field (has a start date and end date value, both YYYY-MM-DD)&lt;/td&gt;&lt;tr&gt;&lt;td&gt;`address`&lt;/td&gt;&lt;td&gt;Address field&lt;/dd&gt;&lt;/table&gt;</summary>
        public global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_field_type? FieldType { get; set; }
        /// <summary>Configuration for highlighting the field at specific stages.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_important_fields? ImportantFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_important_fields ImportantFields { get; set; }
#endif
        /// <summary>Field options (required for enum and set field types)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_options>? Options { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_options> Options { get; set; }
#endif
        /// <summary>Required fields configuration for marking the field as mandatory when interacted with in the Pipedrive web UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_required_fields? RequiredFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_required_fields RequiredFields { get; set; }
#endif
        /// <summary>UI visibility settings for the field. Controls where the field appears in the Pipedrive web UI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_ui_visibility? UiVisibility { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_ui_visibility UiVisibility { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody"/> and sets the default values.
        /// </summary>
        public ProjectFieldsPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "field_name", n => { FieldName = n.GetStringValue(); } },
                { "field_type", n => { FieldType = n.GetEnumValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_field_type>(); } },
                { "important_fields", n => { ImportantFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_important_fields>(global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_important_fields.CreateFromDiscriminatorValue); } },
                { "options", n => { Options = n.GetCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_options>(global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_options.CreateFromDiscriminatorValue)?.AsList(); } },
                { "required_fields", n => { RequiredFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_required_fields>(global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_required_fields.CreateFromDiscriminatorValue); } },
                { "ui_visibility", n => { UiVisibility = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_ui_visibility>(global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_ui_visibility.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("field_name", FieldName);
            writer.WriteEnumValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_field_type>("field_type", FieldType);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_important_fields>("important_fields", ImportantFields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_options>("options", Options);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_required_fields>("required_fields", RequiredFields);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.ProjectFields.ProjectFieldsPostRequestBody_ui_visibility>("ui_visibility", UiVisibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
