// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Persons.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetInclude_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "next_activity_id")]
        #pragma warning disable CS1591
        Next_activity_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_activity_id")]
        #pragma warning disable CS1591
        Last_activity_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "open_deals_count")]
        #pragma warning disable CS1591
        Open_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_open_deals_count")]
        #pragma warning disable CS1591
        Related_open_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed_deals_count")]
        #pragma warning disable CS1591
        Closed_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_closed_deals_count")]
        #pragma warning disable CS1591
        Related_closed_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "participant_open_deals_count")]
        #pragma warning disable CS1591
        Participant_open_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "participant_closed_deals_count")]
        #pragma warning disable CS1591
        Participant_closed_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_messages_count")]
        #pragma warning disable CS1591
        Email_messages_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "activities_count")]
        #pragma warning disable CS1591
        Activities_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "done_activities_count")]
        #pragma warning disable CS1591
        Done_activities_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "undone_activities_count")]
        #pragma warning disable CS1591
        Undone_activities_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "files_count")]
        #pragma warning disable CS1591
        Files_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes_count")]
        #pragma warning disable CS1591
        Notes_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "followers_count")]
        #pragma warning disable CS1591
        Followers_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "won_deals_count")]
        #pragma warning disable CS1591
        Won_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_won_deals_count")]
        #pragma warning disable CS1591
        Related_won_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "lost_deals_count")]
        #pragma warning disable CS1591
        Lost_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_lost_deals_count")]
        #pragma warning disable CS1591
        Related_lost_deals_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_incoming_mail_time")]
        #pragma warning disable CS1591
        Last_incoming_mail_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_outgoing_mail_time")]
        #pragma warning disable CS1591
        Last_outgoing_mail_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "marketing_status")]
        #pragma warning disable CS1591
        Marketing_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "doi_status")]
        #pragma warning disable CS1591
        Doi_status,
        #pragma warning restore CS1591
        [EnumMember(Value = "smart_bcc_email")]
        #pragma warning disable CS1591
        Smart_bcc_email,
        #pragma warning restore CS1591
    }
}
