// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Persons.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PersonsPatchRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation date and time of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>An object where each key represents a custom field. All custom fields are referenced as randomly generated 40-character hashes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_custom_fields CustomFields { get; set; }
#endif
        /// <summary>The emails of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_emails>? Emails { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_emails> Emails { get; set; }
#endif
        /// <summary>The IDs of labels assigned to the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? LabelIds { get; set; }
#nullable restore
#else
        public List<int?> LabelIds { get; set; }
#endif
        /// <summary>If the person does not have a valid email address, then the marketing status is **not set** and `no_consent` is returned for the `marketing_status` value when the new person is created. If the change is forbidden, the status will remain unchanged for every call that tries to modify the marketing status. Please be aware that it is only allowed **once** to change the marketing status from an old status to a new one.&lt;table&gt;&lt;tr&gt;&lt;th&gt;Value&lt;/th&gt;&lt;th&gt;Description&lt;/th&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;`no_consent`&lt;/td&gt;&lt;td&gt;The customer has not given consent to receive any marketing communications&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;`unsubscribed`&lt;/td&gt;&lt;td&gt;The customers have unsubscribed from ALL marketing communications&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;`subscribed`&lt;/td&gt;&lt;td&gt;The customers are subscribed and are counted towards marketing caps&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td&gt;`archived`&lt;/td&gt;&lt;td&gt;The customers with `subscribed` status can be moved to `archived` to save consent, but they are not paid for&lt;/td&gt;&lt;/tr&gt;&lt;/table&gt;</summary>
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_marketing_status? MarketingStatus { get; set; }
        /// <summary>The name of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the organization linked to the person</summary>
        public int? OrgId { get; set; }
        /// <summary>The ID of the user who owns the person</summary>
        public int? OwnerId { get; set; }
        /// <summary>The phones of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_phones>? Phones { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_phones> Phones { get; set; }
#endif
        /// <summary>The last updated date and time of the person</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>The visibility of the person</summary>
        public int? VisibleTo { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody"/> and sets the default values.
        /// </summary>
        public PersonsPatchRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_custom_fields>(global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_custom_fields.CreateFromDiscriminatorValue); } },
                { "emails", n => { Emails = n.GetCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_emails>(global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_emails.CreateFromDiscriminatorValue)?.AsList(); } },
                { "label_ids", n => { LabelIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "marketing_status", n => { MarketingStatus = n.GetEnumValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_marketing_status>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "org_id", n => { OrgId = n.GetIntValue(); } },
                { "owner_id", n => { OwnerId = n.GetIntValue(); } },
                { "phones", n => { Phones = n.GetCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_phones>(global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_phones.CreateFromDiscriminatorValue)?.AsList(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
                { "visible_to", n => { VisibleTo = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_custom_fields>("custom_fields", CustomFields);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_emails>("emails", Emails);
            writer.WriteCollectionOfPrimitiveValues<int?>("label_ids", LabelIds);
            writer.WriteEnumValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_marketing_status>("marketing_status", MarketingStatus);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("org_id", OrgId);
            writer.WriteIntValue("owner_id", OwnerId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.PersonsPatchRequestBody_phones>("phones", Phones);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteIntValue("visible_to", VisibleTo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
