// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Products.Item
{
    /// <summary>Only available in Growth and above plansHow often a customer is billed for access to a service or product</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProductsPatchRequestBody_billing_frequency
    {
        [EnumMember(Value = "one-time")]
        #pragma warning disable CS1591
        OneTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "annually")]
        #pragma warning disable CS1591
        Annually,
        #pragma warning restore CS1591
        [EnumMember(Value = "semi-annually")]
        #pragma warning disable CS1591
        SemiAnnually,
        #pragma warning restore CS1591
        [EnumMember(Value = "quarterly")]
        #pragma warning disable CS1591
        Quarterly,
        #pragma warning restore CS1591
        [EnumMember(Value = "monthly")]
        #pragma warning disable CS1591
        Monthly,
        #pragma warning restore CS1591
        [EnumMember(Value = "weekly")]
        #pragma warning disable CS1591
        Weekly,
        #pragma warning restore CS1591
    }
}
