// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Deals.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetInclude_fieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "next_activity_id")]
        #pragma warning disable CS1591
        Next_activity_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_activity_id")]
        #pragma warning disable CS1591
        Last_activity_id,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_won_time")]
        #pragma warning disable CS1591
        First_won_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "products_count")]
        #pragma warning disable CS1591
        Products_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "files_count")]
        #pragma warning disable CS1591
        Files_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes_count")]
        #pragma warning disable CS1591
        Notes_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "followers_count")]
        #pragma warning disable CS1591
        Followers_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_messages_count")]
        #pragma warning disable CS1591
        Email_messages_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "activities_count")]
        #pragma warning disable CS1591
        Activities_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "done_activities_count")]
        #pragma warning disable CS1591
        Done_activities_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "undone_activities_count")]
        #pragma warning disable CS1591
        Undone_activities_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "participants_count")]
        #pragma warning disable CS1591
        Participants_count,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_incoming_mail_time")]
        #pragma warning disable CS1591
        Last_incoming_mail_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_outgoing_mail_time")]
        #pragma warning disable CS1591
        Last_outgoing_mail_time,
        #pragma warning restore CS1591
        [EnumMember(Value = "smart_bcc_email")]
        #pragma warning disable CS1591
        Smart_bcc_email,
        #pragma warning restore CS1591
        [EnumMember(Value = "source_lead_id")]
        #pragma warning disable CS1591
        Source_lead_id,
        #pragma warning restore CS1591
    }
}
