// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.Lead;
using Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.Status;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace
{
    /// <summary>
    /// Builds and executes requests for operations under \deals\{id}\convert
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConvertRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lead property</summary>
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.Lead.LeadRequestBuilder Lead
        {
            get => new global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.Lead.LeadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.ConvertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deals/{id}/convert", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.ConvertNamespace.ConvertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConvertRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deals/{id}/convert", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
