// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    /// <summary>
    /// UI visibility settings for the field. Controls where the field appears in the Pipedrive web UI.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AddDealFieldRequestUiVisibility : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the field is shown in the add deal modal. Default is false. Cannot be set to false for required system fields (title, pipeline, stage_id, probability).</summary>
        public bool? AddVisibleFlag { get; set; }
        /// <summary>Whether the field is shown in the deal details view. Default is true.</summary>
        public bool? DetailsVisibleFlag { get; set; }
        /// <summary>Whether the field is shown in the project details view when the deal is linked to a project. Default is false.</summary>
        public bool? ProjectsDetailVisibleFlag { get; set; }
        /// <summary>Controls which pipelines display this field. Default is show_in_all=true. Note that fields marked as important or required must be visible in the pipelines where they are configured.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibilityShowInPipelines? ShowInPipelines { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibilityShowInPipelines ShowInPipelines { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibility"/> and sets the default values.
        /// </summary>
        public AddDealFieldRequestUiVisibility()
        {
            AdditionalData = new Dictionary<string, object>();
            AddVisibleFlag = false;
            DetailsVisibleFlag = true;
            ProjectsDetailVisibleFlag = false;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibility"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibility CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibility();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_visible_flag", n => { AddVisibleFlag = n.GetBoolValue(); } },
                { "details_visible_flag", n => { DetailsVisibleFlag = n.GetBoolValue(); } },
                { "projects_detail_visible_flag", n => { ProjectsDetailVisibleFlag = n.GetBoolValue(); } },
                { "show_in_pipelines", n => { ShowInPipelines = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibilityShowInPipelines>(global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibilityShowInPipelines.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("add_visible_flag", AddVisibleFlag);
            writer.WriteBoolValue("details_visible_flag", DetailsVisibleFlag);
            writer.WriteBoolValue("projects_detail_visible_flag", ProjectsDetailVisibleFlag);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.AddDealFieldRequestUiVisibilityShowInPipelines>("show_in_pipelines", ShowInPipelines);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
