// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    /// <summary>The value of the discount. The `discount_type` field can be used to specify whether the value is an amount or a percentage</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AddDealProductRequestDiscountType
    {
        [EnumMember(Value = "percentage")]
        #pragma warning disable CS1591
        Percentage,
        #pragma warning restore CS1591
        [EnumMember(Value = "amount")]
        #pragma warning disable CS1591
        Amount,
        #pragma warning restore CS1591
    }
}
