// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetActivitiesIncludeFieldsParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "attendees")]
        #pragma warning disable CS1591
        Attendees,
        #pragma warning restore CS1591
    }
}
