// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetArchivedDealsIncludeFieldsParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "next_activity_id")]
        #pragma warning disable CS1591
        NextActivityId,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_activity_id")]
        #pragma warning disable CS1591
        LastActivityId,
        #pragma warning restore CS1591
        [EnumMember(Value = "first_won_time")]
        #pragma warning disable CS1591
        FirstWonTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "products_count")]
        #pragma warning disable CS1591
        ProductsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "files_count")]
        #pragma warning disable CS1591
        FilesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes_count")]
        #pragma warning disable CS1591
        NotesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "followers_count")]
        #pragma warning disable CS1591
        FollowersCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_messages_count")]
        #pragma warning disable CS1591
        EmailMessagesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "activities_count")]
        #pragma warning disable CS1591
        ActivitiesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "done_activities_count")]
        #pragma warning disable CS1591
        DoneActivitiesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "undone_activities_count")]
        #pragma warning disable CS1591
        UndoneActivitiesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "participants_count")]
        #pragma warning disable CS1591
        ParticipantsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_incoming_mail_time")]
        #pragma warning disable CS1591
        LastIncomingMailTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_outgoing_mail_time")]
        #pragma warning disable CS1591
        LastOutgoingMailTime,
        #pragma warning restore CS1591
        [EnumMember(Value = "smart_bcc_email")]
        #pragma warning disable CS1591
        SmartBccEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "source_lead_id")]
        #pragma warning disable CS1591
        SourceLeadId,
        #pragma warning restore CS1591
    }
}
