// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetConvertResponseResponseApplicationJson : ApiException, IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The additional_dataProperty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_additional_data? AdditionalDataProperty { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_additional_data AdditionalDataProperty { get; set; }
#endif
        /// <summary>An object containing conversion status. After successful conversion the converted entity ID is also present.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_data? DataEscaped { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_data DataEscaped { get; set; }
#endif
        /// <summary>The primary error message.</summary>
        public override string Message { get => base.Message; }
        /// <summary>The success property</summary>
        public bool? Success { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson"/> and sets the default values.
        /// </summary>
        public GetConvertResponseResponseApplicationJson()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "additional_data", n => { AdditionalDataProperty = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_additional_data>(global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_additional_data.CreateFromDiscriminatorValue); } },
                { "data", n => { DataEscaped = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_data>(global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_data.CreateFromDiscriminatorValue); } },
                { "success", n => { Success = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_additional_data>("additional_data", AdditionalDataProperty);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetConvertResponseResponseApplicationJson_data>("data", DataEscaped);
            writer.WriteBoolValue("success", Success);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
