// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetOrganizationsResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address of the organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_address? Address { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_address Address { get; set; }
#endif
        /// <summary>The creation date and time of the organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>The annual revenue of the organization</summary>
        public int? AnnualRevenue { get; set; }
        /// <summary>An object where each key represents a custom field. All custom fields are referenced as randomly generated 40-character hashes. To clear a custom field value, set it to `null`. For multi-option fields (field type `set`), use `null` to clear the selection — sending an empty array `[]` is not supported and will result in a validation error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_custom_fields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_custom_fields CustomFields { get; set; }
#endif
        /// <summary>The number of employees in the organization</summary>
        public int? EmployeeCount { get; set; }
        /// <summary>The ID of the organization</summary>
        public int? Id { get; set; }
        /// <summary>The industry the organization belongs to</summary>
        public int? Industry { get; set; }
        /// <summary>Whether the organization is deleted or not</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>The IDs of labels assigned to the organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? LabelIds { get; set; }
#nullable restore
#else
        public List<int?> LabelIds { get; set; }
#endif
        /// <summary>The LinkedIn profile URL of the organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Linkedin { get; set; }
#nullable restore
#else
        public string Linkedin { get; set; }
#endif
        /// <summary>The name of the organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the user who owns the organization</summary>
        public int? OwnerId { get; set; }
        /// <summary>The last updated date and time of the organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>The visibility of the organization</summary>
        public int? VisibleTo { get; set; }
        /// <summary>The website of the organization</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Website { get; set; }
#nullable restore
#else
        public string Website { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data"/> and sets the default values.
        /// </summary>
        public GetOrganizationsResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "address", n => { Address = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_address>(global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_address.CreateFromDiscriminatorValue); } },
                { "annual_revenue", n => { AnnualRevenue = n.GetIntValue(); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_custom_fields>(global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_custom_fields.CreateFromDiscriminatorValue); } },
                { "employee_count", n => { EmployeeCount = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "industry", n => { Industry = n.GetIntValue(); } },
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "label_ids", n => { LabelIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "linkedin", n => { Linkedin = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner_id", n => { OwnerId = n.GetIntValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
                { "visible_to", n => { VisibleTo = n.GetIntValue(); } },
                { "website", n => { Website = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_address>("address", Address);
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteIntValue("annual_revenue", AnnualRevenue);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.GetOrganizationsResponse_data_custom_fields>("custom_fields", CustomFields);
            writer.WriteIntValue("employee_count", EmployeeCount);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("industry", Industry);
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteCollectionOfPrimitiveValues<int?>("label_ids", LabelIds);
            writer.WriteStringValue("linkedin", Linkedin);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("owner_id", OwnerId);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteIntValue("visible_to", VisibleTo);
            writer.WriteStringValue("website", Website);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
