// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrganizationIncludeFieldsParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "next_activity_id")]
        #pragma warning disable CS1591
        NextActivityId,
        #pragma warning restore CS1591
        [EnumMember(Value = "last_activity_id")]
        #pragma warning disable CS1591
        LastActivityId,
        #pragma warning restore CS1591
        [EnumMember(Value = "open_deals_count")]
        #pragma warning disable CS1591
        OpenDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_open_deals_count")]
        #pragma warning disable CS1591
        RelatedOpenDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "closed_deals_count")]
        #pragma warning disable CS1591
        ClosedDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_closed_deals_count")]
        #pragma warning disable CS1591
        RelatedClosedDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "email_messages_count")]
        #pragma warning disable CS1591
        EmailMessagesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "people_count")]
        #pragma warning disable CS1591
        PeopleCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "activities_count")]
        #pragma warning disable CS1591
        ActivitiesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "done_activities_count")]
        #pragma warning disable CS1591
        DoneActivitiesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "undone_activities_count")]
        #pragma warning disable CS1591
        UndoneActivitiesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "files_count")]
        #pragma warning disable CS1591
        FilesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes_count")]
        #pragma warning disable CS1591
        NotesCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "followers_count")]
        #pragma warning disable CS1591
        FollowersCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "won_deals_count")]
        #pragma warning disable CS1591
        WonDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_won_deals_count")]
        #pragma warning disable CS1591
        RelatedWonDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "lost_deals_count")]
        #pragma warning disable CS1591
        LostDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "related_lost_deals_count")]
        #pragma warning disable CS1591
        RelatedLostDealsCount,
        #pragma warning restore CS1591
        [EnumMember(Value = "smart_bcc_email")]
        #pragma warning disable CS1591
        SmartBccEmail,
        #pragma warning restore CS1591
    }
}
