// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateProductResponseData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date and time when the product was added</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>Only available in Growth and above plansHow often a customer is billed for access to a service or product</summary>
        public global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataBillingFrequency? BillingFrequency { get; set; }
        /// <summary>Only available in Growth and above plansThe number of times the billing frequency repeats for a product in a dealWhen `billing_frequency` is set to `one-time`, this field must be `null`When `billing_frequency` is set to `weekly`, this field cannot be `null`For all the other values of `billing_frequency`, `null` represents a product billed indefinitelyMust be a positive integer less or equal to 208</summary>
        public int? BillingFrequencyCycles { get; set; }
        /// <summary>The category of the product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Category { get; set; }
#nullable restore
#else
        public string Category { get; set; }
#endif
        /// <summary>The product code</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>An object where each key represents a custom field. All custom fields are referenced as randomly generated 40-character hashes. To clear a custom field value, set it to `null`. For multi-option fields (field type `set`), use `null` to clear the selection — sending an empty array `[]` is not supported and will result in a validation error.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataCustomFields? CustomFields { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataCustomFields CustomFields { get; set; }
#endif
        /// <summary>The description of the product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of the product</summary>
        public int? Id { get; set; }
        /// <summary>Whether this product will be marked as deleted or not</summary>
        public bool? IsDeleted { get; set; }
        /// <summary>Whether this product can be added to a deal or not</summary>
        public bool? IsLinkable { get; set; }
        /// <summary>The name of the product</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The ID of the Pipedrive user who owns the product</summary>
        public int? OwnerId { get; set; }
        /// <summary>The prices of the product in different currencies</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataPricesItem>? Prices { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataPricesItem> Prices { get; set; }
#endif
        /// <summary>The tax percentage</summary>
        public double? Tax { get; set; }
        /// <summary>The unit in which this product is sold</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Unit { get; set; }
#nullable restore
#else
        public string Unit { get; set; }
#endif
        /// <summary>The date and time when the product was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>Visibility of the product</summary>
        public double? VisibleTo { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseData"/> and sets the default values.
        /// </summary>
        public UpdateProductResponseData()
        {
            AdditionalData = new Dictionary<string, object>();
            BillingFrequency = global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataBillingFrequency.OneTime;
            IsDeleted = false;
            IsLinkable = true;
            Tax = 0;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "billing_frequency", n => { BillingFrequency = n.GetEnumValue<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataBillingFrequency>(); } },
                { "billing_frequency_cycles", n => { BillingFrequencyCycles = n.GetIntValue(); } },
                { "category", n => { Category = n.GetStringValue(); } },
                { "code", n => { Code = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataCustomFields>(global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataCustomFields.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_deleted", n => { IsDeleted = n.GetBoolValue(); } },
                { "is_linkable", n => { IsLinkable = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner_id", n => { OwnerId = n.GetIntValue(); } },
                { "prices", n => { Prices = n.GetCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataPricesItem>(global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataPricesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "tax", n => { Tax = n.GetDoubleValue(); } },
                { "unit", n => { Unit = n.GetStringValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
                { "visible_to", n => { VisibleTo = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteEnumValue<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataBillingFrequency>("billing_frequency", BillingFrequency);
            writer.WriteIntValue("billing_frequency_cycles", BillingFrequencyCycles);
            writer.WriteStringValue("category", Category);
            writer.WriteStringValue("code", Code);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataCustomFields>("custom_fields", CustomFields);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_deleted", IsDeleted);
            writer.WriteBoolValue("is_linkable", IsLinkable);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("owner_id", OwnerId);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pipedrive.OpenApiClient.Models.UpdateProductResponseDataPricesItem>("prices", Prices);
            writer.WriteDoubleValue("tax", Tax);
            writer.WriteStringValue("unit", Unit);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteDoubleValue("visible_to", VisibleTo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
