// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Deals.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetStatusQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "open")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "won")]
        #pragma warning disable CS1591
        Won,
        #pragma warning restore CS1591
        [EnumMember(Value = "lost")]
        #pragma warning disable CS1591
        Lost,
        #pragma warning restore CS1591
    }
}
