// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Deals.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SearchGetResponse_data_items_item : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The currency of the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>Custom fields</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomFields { get; set; }
#nullable restore
#else
        public List<string> CustomFields { get; set; }
#endif
        /// <summary>The ID of the deal</summary>
        public int? Id { get; set; }
        /// <summary>A flag indicating whether the deal is archived or not</summary>
        public bool? IsArchived { get; set; }
        /// <summary>An array of notes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Notes { get; set; }
#nullable restore
#else
        public List<string> Notes { get; set; }
#endif
        /// <summary>The organization property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_organization? Organization { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_organization Organization { get; set; }
#endif
        /// <summary>The owner property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_owner? Owner { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_owner Owner { get; set; }
#endif
        /// <summary>The person property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_person? Person { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_person Person { get; set; }
#endif
        /// <summary>The stage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_stage? Stage { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_stage Stage { get; set; }
#endif
        /// <summary>The status of the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The title of the deal</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The type of the item</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The value of the deal</summary>
        public int? Value { get; set; }
        /// <summary>The visibility of the deal</summary>
        public int? VisibleTo { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item"/> and sets the default values.
        /// </summary>
        public SearchGetResponse_data_items_item()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "custom_fields", n => { CustomFields = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_archived", n => { IsArchived = n.GetBoolValue(); } },
                { "notes", n => { Notes = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "organization", n => { Organization = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_organization>(global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_organization.CreateFromDiscriminatorValue); } },
                { "owner", n => { Owner = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_owner>(global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_owner.CreateFromDiscriminatorValue); } },
                { "person", n => { Person = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_person>(global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_person.CreateFromDiscriminatorValue); } },
                { "stage", n => { Stage = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_stage>(global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_stage.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "value", n => { Value = n.GetIntValue(); } },
                { "visible_to", n => { VisibleTo = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("currency", Currency);
            writer.WriteCollectionOfPrimitiveValues<string>("custom_fields", CustomFields);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_archived", IsArchived);
            writer.WriteCollectionOfPrimitiveValues<string>("notes", Notes);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_organization>("organization", Organization);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_owner>("owner", Owner);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_person>("person", Person);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Search.SearchGetResponse_data_items_item_stage>("stage", Stage);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("type", Type);
            writer.WriteIntValue("value", Value);
            writer.WriteIntValue("visible_to", VisibleTo);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
