// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts
{
    /// <summary>Determines whether the discount is applied as a percentage or a fixed amount.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DiscountsPostResponse_data_type
    {
        [EnumMember(Value = "percentage")]
        #pragma warning disable CS1591
        Percentage,
        #pragma warning restore CS1591
        [EnumMember(Value = "amount")]
        #pragma warning disable CS1591
        Amount,
        #pragma warning restore CS1591
    }
}
