// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DiscountsGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The discount amount.</summary>
        public double? Amount { get; set; }
        /// <summary>The date and time of when the discount was created in the ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The ID of the user that created the discount.</summary>
        public int? CreatedBy { get; set; }
        /// <summary>The ID of the deal the discount was added to.</summary>
        public int? DealId { get; set; }
        /// <summary>The name of the discount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The ID of the additional discount</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Determines whether the discount is applied as a percentage or a fixed amount.</summary>
        public global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts.DiscountsGetResponse_data_type? Type { get; set; }
        /// <summary>The date and time of when the discount was created in the ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>The ID of the user that last updated the discount.</summary>
        public int? UpdatedBy { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts.DiscountsGetResponse_data"/> and sets the default values.
        /// </summary>
        public DiscountsGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts.DiscountsGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts.DiscountsGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts.DiscountsGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetDoubleValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "created_by", n => { CreatedBy = n.GetIntValue(); } },
                { "deal_id", n => { DealId = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts.DiscountsGetResponse_data_type>(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "updated_by", n => { UpdatedBy = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount", Amount);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteIntValue("created_by", CreatedBy);
            writer.WriteIntValue("deal_id", DealId);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.Pipedrive.OpenApiClient.Deals.Item.Discounts.DiscountsGetResponse_data_type>("type", Type);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteIntValue("updated_by", UpdatedBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
