// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PictureGetResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Whether the picture is active or not.</summary>
        public bool? ActiveFlag { get; set; }
        /// <summary>The ID of the user who added the picture.</summary>
        public int? AddedByUserId { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The file size in bytes.</summary>
        public int? FileSize { get; set; }
        /// <summary>The ID of the picture.</summary>
        public int? Id { get; set; }
        /// <summary>The ID of the person this picture belongs to.</summary>
        public int? ItemId { get; set; }
        /// <summary>The type of item the picture is associated with.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemType { get; set; }
#nullable restore
#else
        public string ItemType { get; set; }
#endif
        /// <summary>Picture URLs indexed by size.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data_pictures? Pictures { get; set; }
#nullable restore
#else
        public global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data_pictures Pictures { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data"/> and sets the default values.
        /// </summary>
        public PictureGetResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active_flag", n => { ActiveFlag = n.GetBoolValue(); } },
                { "added_by_user_id", n => { AddedByUserId = n.GetIntValue(); } },
                { "file_size", n => { FileSize = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "item_id", n => { ItemId = n.GetIntValue(); } },
                { "item_type", n => { ItemType = n.GetStringValue(); } },
                { "pictures", n => { Pictures = n.GetObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data_pictures>(global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data_pictures.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active_flag", ActiveFlag);
            writer.WriteIntValue("added_by_user_id", AddedByUserId);
            writer.WriteIntValue("file_size", FileSize);
            writer.WriteIntValue("id", Id);
            writer.WriteIntValue("item_id", ItemId);
            writer.WriteStringValue("item_type", ItemType);
            writer.WriteObjectValue<global::Soenneker.Pipedrive.OpenApiClient.Persons.Item.Picture.PictureGetResponse_data_pictures>("pictures", Pictures);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
