// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Tasks.Item
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TasksPatchResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The creation date and time of the task in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddTime { get; set; }
#nullable restore
#else
        public string AddTime { get; set; }
#endif
        /// <summary>The IDs of users assigned to the task</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? AssigneeIds { get; set; }
#nullable restore
#else
        public List<int?> AssigneeIds { get; set; }
#endif
        /// <summary>The ID of the user who created the task</summary>
        public int? CreatorId { get; set; }
        /// <summary>The description of the task</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The due date of the task. Format: YYYY-MM-DD.</summary>
        public Date? DueDate { get; set; }
        /// <summary>The ID of the task</summary>
        public int? Id { get; set; }
        /// <summary>Whether the task is done or not.</summary>
        public bool? IsDone { get; set; }
        /// <summary>Whether the task is a milestone or not.</summary>
        public bool? IsMilestone { get; set; }
        /// <summary>The date and time the task was marked as done in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MarkedAsDoneTime { get; set; }
#nullable restore
#else
        public string MarkedAsDoneTime { get; set; }
#endif
        /// <summary>The ID of the parent task. If `null`, the task is a root-level task.</summary>
        public int? ParentTaskId { get; set; }
        /// <summary>The priority of the task</summary>
        public int? Priority { get; set; }
        /// <summary>The ID of the project this task is associated with</summary>
        public int? ProjectId { get; set; }
        /// <summary>The start date of the task. Format: YYYY-MM-DD.</summary>
        public Date? StartDate { get; set; }
        /// <summary>The title of the task</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The update date and time of the task in ISO 8601 format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdateTime { get; set; }
#nullable restore
#else
        public string UpdateTime { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pipedrive.OpenApiClient.Tasks.Item.TasksPatchResponse_data"/> and sets the default values.
        /// </summary>
        public TasksPatchResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pipedrive.OpenApiClient.Tasks.Item.TasksPatchResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pipedrive.OpenApiClient.Tasks.Item.TasksPatchResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pipedrive.OpenApiClient.Tasks.Item.TasksPatchResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "add_time", n => { AddTime = n.GetStringValue(); } },
                { "assignee_ids", n => { AssigneeIds = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "creator_id", n => { CreatorId = n.GetIntValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "due_date", n => { DueDate = n.GetDateValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "is_done", n => { IsDone = n.GetBoolValue(); } },
                { "is_milestone", n => { IsMilestone = n.GetBoolValue(); } },
                { "marked_as_done_time", n => { MarkedAsDoneTime = n.GetStringValue(); } },
                { "parent_task_id", n => { ParentTaskId = n.GetIntValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "project_id", n => { ProjectId = n.GetIntValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "update_time", n => { UpdateTime = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("add_time", AddTime);
            writer.WriteCollectionOfPrimitiveValues<int?>("assignee_ids", AssigneeIds);
            writer.WriteIntValue("creator_id", CreatorId);
            writer.WriteStringValue("description", Description);
            writer.WriteDateValue("due_date", DueDate);
            writer.WriteIntValue("id", Id);
            writer.WriteBoolValue("is_done", IsDone);
            writer.WriteBoolValue("is_milestone", IsMilestone);
            writer.WriteStringValue("marked_as_done_time", MarkedAsDoneTime);
            writer.WriteIntValue("parent_task_id", ParentTaskId);
            writer.WriteIntValue("priority", Priority);
            writer.WriteIntValue("project_id", ProjectId);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("update_time", UpdateTime);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
