// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.Projects.Search
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFieldsQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "custom_fields")]
        #pragma warning disable CS1591
        Custom_fields,
        #pragma warning restore CS1591
        [EnumMember(Value = "notes")]
        #pragma warning disable CS1591
        Notes,
        #pragma warning restore CS1591
        [EnumMember(Value = "title")]
        #pragma warning disable CS1591
        Title,
        #pragma warning restore CS1591
        [EnumMember(Value = "description")]
        #pragma warning disable CS1591
        Description,
        #pragma warning restore CS1591
    }
}
