// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pipedrive.OpenApiClient.ItemSearch
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetItem_typesQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "deal")]
        #pragma warning disable CS1591
        Deal,
        #pragma warning restore CS1591
        [EnumMember(Value = "person")]
        #pragma warning disable CS1591
        Person,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization")]
        #pragma warning disable CS1591
        Organization,
        #pragma warning restore CS1591
        [EnumMember(Value = "product")]
        #pragma warning disable CS1591
        Product,
        #pragma warning restore CS1591
        [EnumMember(Value = "lead")]
        #pragma warning disable CS1591
        Lead,
        #pragma warning restore CS1591
        [EnumMember(Value = "file")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
        [EnumMember(Value = "mail_attachment")]
        #pragma warning disable CS1591
        Mail_attachment,
        #pragma warning restore CS1591
        [EnumMember(Value = "project")]
        #pragma warning disable CS1591
        Project,
        #pragma warning restore CS1591
    }
}
